### ISSUE TITLE
BUG反馈：屏幕最小宽度dp>600时，相机闪退！

### ISSUE THREAD

**Issue by Lontern-520** [a406010503/Miui_Camera#53]
java.lang.ClassCastException: android.widget.RelativeLayout$LayoutParams cannot be cast to android.widget.FrameLayout$LayoutParams
 at com.android.camera2.compat.theme.custom.cv.MiThemeOperationBottomCV.alignSnapLeftByDefault(Unknown Source:14)
 at com.android.camera.fragment.bottom.action.FragmentBottomAction.updateLayout(Unknown Source:512)
 at com.android.camera.fragment.bottom.action.FragmentBottomAction.updateView(Unknown Source:4)
 at com.android.camera.fragment.BaseFragment.onViewCreated(Unknown Source:3)
 at androidx.fragment.app.Fragment.performViewCreated(Unknown Source:4)
 at androidx.fragment.app.FragmentStateManager.createView(Unknown Source:263)
 at androidx.fragment.app.FragmentStateManager.moveToExpectedState(Unknown Source:116)
 at androidx.fragment.app.FragmentManager.executeOpsTogether(Unknown Source:277)
 at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(Unknown Source:84)
 at androidx.fragment.app.FragmentManager.execPendingActions(Unknown Source:21)
 at androidx.fragment.app.FragmentManager.dispatchStateChange(Unknown Source:42)
 at androidx.fragment.app.FragmentManager.dispatchActivityCreated(Unknown Source:11)
 at androidx.fragment.app.FragmentController.dispatchActivityCreated(Unknown Source:4)
 at androidx.fragment.app.FragmentActivity.onStart(Unknown Source:15)
 at com.android.camera.ActivityBase.onStart(Unknown Source:33)
 at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1467)
 at android.app.Activity.performStart(Activity.java:8310)
 at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3784)
 at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
 at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
 at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2282)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:210)
 at android.os.Looper.loop(Looper.java:299)
 at android.app.ActivityThread.main(ActivityThread.java:8212)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by a406010503** [comment]
這是你修改 dpi 造成的，非相機問題，故關閉此問題。
