### ISSUE TITLE
1080 960 FPS on 11t pro crash

### ISSUE THREAD

**Issue by ammlr** [a406010503/Miui_Camera#9]
this is log

[Device Brand]: Xiaomi
[Device Model]: 2107113SG
[Display]: SKQ1.211006.001 test-keys
[Android Version]: 12
[API Version]: 31
[Package Name]: com.android.camera
[Error Type]: Jvm
[Crash Time]: 25 Agu 2022 00.39.42
[Stack Trace]:
io.reactivex.exceptions.UndeliverableException: java.lang.UnsatisfiedLinkError: No implementation found for int com.miui.extravideoxmalgo.xiaomiAlgoInterpolator.XiaomiAlgoInterpolatorJNI.MiVideoMeinInit(int, int, int, int) (tried Java_com_miui_extravideoxmalgo_xiaomiAlgoInterpolator_XiaomiAlgoInterpolatorJNI_MiVideoMeinInit and Java_com_miui_extravideoxmalgo_xiaomiAlgoInterpolator_XiaomiAlgoInterpolatorJNI_MiVideoMeinInit__IIII)
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:4)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:3)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.UnsatisfiedLinkError: No implementation found for int com.miui.extravideoxmalgo.xiaomiAlgoInterpolator.XiaomiAlgoInterpolatorJNI.MiVideoMeinInit(int, int, int, int) (tried Java_com_miui_extravideoxmalgo_xiaomiAlgoInterpolator_XiaomiAlgoInterpolatorJNI_MiVideoMeinInit and Java_com_miui_extravideoxmalgo_xiaomiAlgoInterpolator_XiaomiAlgoInterpolatorJNI_MiVideoMeinInit__IIII)
	at com.miui.extravideoxmalgo.xiaomiAlgoInterpolator.XiaomiAlgoInterpolatorJNI.MiVideoMeinInit(Native Method)
	at com.miui.extravideoxmalgo.xiaomiAlgoInterpolator.XiaomiAlgoInterpolatorJNI.initializeAlgo(XiaomiAlgoInterpolatorJNI.java:1)
	at com.miui.extravideoxmalgo.xiaomiAlgoInterpolator.XiaomiAlgoMediaInterpolator.init(XiaomiAlgoMediaInterpolator.java:6)
	at com.android.camera.module.video.SlowMotionModule.OooOOO(SlowMotionModule.java:2)
	at OooO0O0.OooO0O0.OooO00o.OooooOo.o00O0O00.OooOOO.run(Unknown Source:2)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:2)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:2)
	... 6 more

**Comment by a406010503** [comment]
This is a known issue, please verify this in subsequent releases.
